### ISSUE TITLE
Navigating from certain pages causing 404s

### ISSUE THREAD

**Issue by kellyk** [WriteSpeakCode/2016.writespeakcode.com#11]
When on any page in the Conference dropdown, (such as http://2016.writespeakcode.com/tickets/), using the nav to move to other pages in the Conference dropdown (Tickets, Call for Proposals, Nominate) directs users to non-existent URLs:

http://2016.writespeakcode.com/tickets/tickets.html
http://2016.writespeakcode.com/cfp/tickets.html
etc.

**Comment by carolynvs** [comment]
Sorry I forgot to close this when it was originally fixed! Thank you for reporting the problem.

Fixed in 77374c6fd436ee5b4f88ff0cb65a5384bd93a164
