### ISSUE TITLE
Consider nil AND empty string for speaker and talk info

### ISSUE THREAD

**Issue by rmw** [WriteSpeakCode/2016.writespeakcode.com#40]
For images, social links, etc, we are just checking that the variable exists.  However, when things are created or edited in ActiveAdmin, they are set to an empty string.  We need to check for that as well as `nil`

```
unless person.bio.nil? || person.bio.empty?
```

**Comment by rmw** [comment]
@KaraAJC - Could you grab this whenever you have time this week? (Somewhat urgent)

**Comment by KaraAJC** [comment]
Yes I can!

**Comment by KaraAJC** [comment]
#41 Pull Request addresses this issue

**Comment by rachelober** [comment]
It's fixed

**Comment by rachelober** [comment]
(Thank you Kara!!!)
