### ISSUE TITLE
Google is indexing our https site

### ISSUE THREAD

**Issue by carolynvs** [WriteSpeakCode/2016.writespeakcode.com#9]
When you google our conference, the result is linking to the https url. We never setup TLS for our custom domain in heroku, so the certificate is for our herokuapps domain, and therefore shows up as untrusted.

I think the right answer is to setup a TLS certificate for 2016.writespeakcode.com. Once we have login forms, that is the right thing to do anyway. See https://devcenter.heroku.com/articles/ssl-endpoint for how to setup heroku with a certificate.

Alternatively, we need to disable the https endpoint in heroku and ensure that google uses our http site.

**Comment by rmw** [comment]
@carolynvs I'm looking at getting an SSL cert.  In the mean time, maybe disable the https endpoints in heroku?

**Comment by rmw** [comment]
Removing milestone since don't need to use SSL so far ...

**Comment by rmw** [comment]
Added SSL cert.
